export const question_type_autocomplete = [
  'start',
  'end',
  'today',
  'deviceid',
  'phonenumber',
  'username',
  'email',
  'audit',
  'integer',
  'decimal',
  'range',
  'text',
  'select_one [list_name]',
  'select_multiple [list_name]',
  'select_one_from_file [file_name]',
  'select_multiple_from_file [file_name]',
  'rank [options]',
  'note',
  'geopoint',
  'geotrace',
  'geoshape',
  'date',
  'time',
  'dateTime',
  'image',
  'audio',
  'background-audio',
  'video',
  'file',
  'barcode',
  'calculate',
  'acknowledge',
  'hidden',
  'xml-external',
  'begin group',
  'end group',
  'begin repeat',
  'end repeat',
];
